name: deep_faces
channels:
  - pytorch
  - defaults
  - anaconda
dependencies:
  - pytorch==1.12.1
  - torchvision==0.13.1
  - cudatoolkit=10.2
  - jupyter
  - ipykernel
  - numpy==1.26.4
  - pandas
  - matplotlib
  - scipy
  - scikit-learn
  - scikit-image
  - tqdm